version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    groups:
      gha-low-risk:
        update-types:
          - "minor"
          - "patch"
    cooldown:
      default-days: 7
