name: Tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn lint
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          product-name: Test
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: Generate a VPAT"
          branch: test-vpat-report
          base: main
          title: "docs: Generate a VPAT"
          body: |
            This patch generates a VPAT based on this repository's currently open issues.

            This PR was opened by a robot :robot: :tada:
