name: Tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn lint
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          product-name: Test
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: "docs: Generate a VPAT"
          branch: auto-generate-vpat-report
          base: develop
          title: "docs: Generate a VPAT"
          body: |
            This patch generates a VPAT based on this repository's currently open issues.

            This PR was opened by a robot :robot: :tada:
